# Generated by Django 4.0.6 on 2022-08-15 00:00

import django.core.validators
from django.db import migrations, models
import utils.avatar_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{2,30}$')])),
                ('surname', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{2,30}$')])),
                ('born', models.DateField(blank=True, default='2000-01-01', verbose_name='Date of birth')),
                ('avatar', models.ImageField(blank=True, upload_to=utils.avatar_util.AvatarUtils.upload_to)),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number ex. +380xxxxxxxxx')])),
            ],
            options={
                'verbose_name': 'Profiles of users',
                'verbose_name_plural': 'Profiles of users',
                'db_table': 'profiles',
                'ordering': ['name', 'surname', '-born'],
            },
        ),
    ]
