# Generated by Django 4.0.6 on 2023-01-10 23:36

from django.db import migrations, models
import utils.school_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Ages',
                'verbose_name_plural': 'Ages',
                'db_table': 'ages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Cities',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearnFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Learn formats',
                'verbose_name_plural': 'Learn formats',
                'db_table': 'learn_formats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, default='', upload_to=utils.school_util.SchoolUtils.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ages', models.ManyToManyField(related_name='ages', to='school.agemodel')),
                ('cities', models.ManyToManyField(related_name='cities', to='school.citymodel')),
                ('learn_formats', models.ManyToManyField(related_name='learn_formats', to='school.learnformatmodel')),
            ],
            options={
                'verbose_name': 'Catalog of schools',
                'verbose_name_plural': 'Catalog of schools',
                'db_table': 'school',
                'ordering': ['name'],
            },
        ),
    ]
