# Generated by Django 4.0.6 on 2022-08-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
