# Generated by Django 4.0.6 on 2022-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_citymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmodel',
            name='city',
        ),
        migrations.AddField(
            model_name='schoolmodel',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='school.citymodel'),
        ),
    ]
