# Generated by Django 4.0.6 on 2022-08-30 19:52

from django.db import migrations, models
import utils.school_util


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_schoolmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.school_util.SchoolUtils.upload_to),
        ),
    ]
